# =============================================================================
# MAIN
# =============================================================================
Main:
  profile:    #true
  train:      #true
  validate:   false
  test:       false
  generate:   true

  load_model: true

  img2img: true
  test_image: test_image3.png


# =============================================================================
# TRAINING
# =============================================================================
Training:  
  epochs:           3000
  batch_size:       128
  learning_rate:    4.5e-6
  logging_steps:    10
  num_workers:      8
  Data_Split:       1.0

  generate_after_n: 50

  Save_after_epoch: true
  save_after_n:     15
  backup_after_n:   2

  Validation:
    z_score: 3

# =============================================================================
# MODEL
# =============================================================================
Model:
  # external: cfg/vae/vae.yaml
  # selection: VAE_1x256x256_4x32x32_167k
  # selection: VAE_mnist_simple

  external: cfg/diffusion/ddpm.yaml
  # selection: latent_terrain_diffusion_max_500
  # selection: ltd_v2
  selection: ltd_v3
  # selection: ltd_mnist_variance
  # selection: ltd_mnist_variance_dit

  only_load_selection: true
  read_only: true

# =============================================================================
# Perlin
# =============================================================================
Perlin:
  seed:             42
  lacunarity:       2
  persistance:      0.5
  octaves:          6

  chunks_per_image_side:  2
  image_side_resolution:  256
  cells_per_chunk_side:   2

# =============================================================================
# DATA
# =============================================================================
Data:
  use_MNIST:      # true

  DEM_List:       SRTM_GL1_50_over_list.txt
  DEM_Dataset:    SRTM_GL1_512x512
  Cache_DEMs:     true
  loader_workers: 8
  # < 1 -> We take all in the specified list
  amount_dems:    0

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   true
    use_as_channel: false
    cache:          true
  Climate: 
    use_as_label:   true
    use_as_channel: false
    cache:          true
  
  # Data transforms
  RandomCrop:
    active:         true
    size:           256 
  RandomRotation:
    active:         true 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5

Debug:
  print_only_rank_zero: false
