# =============================================================================
# MAIN
# =============================================================================
Main:
  train:      true
  validate:   false
  test:       false
  generate:   true

  load_model: true

  use_MNIST:  false

# =============================================================================
# TRAINING
# =============================================================================
Training:  
  epochs:           1000
  batch_size:       128
  learning_rate:    4.5e-6
  logging_steps:    10
  num_workers:      2
  Save_after_epoch: true
  Data_Split:       1.0

  Validation:
    z_score: 3

# =============================================================================
# MODEL
# =============================================================================
Model:
  external: cfg/vae/vae.yaml
  selection: VAE_EMA_test_new_attention
  # external: cfg/diffusion/ddpm.yaml
  # selection: ld_finer_classes
  only_load_selection: true
  read_only: true

# =============================================================================
# DATA
# =============================================================================
Data:
  DEM_List:       SRTM_GL1_50_over_list.txt
  DEM_Dataset:    SRTM_GL1_512x512
  Cache_DEMs:     true
  loader_workers: 2
  # < 1 -> We take all in the specified list
  amount_dems:    0

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  Climate: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   true
    use_as_channel: false
    cache:          true
    # use_as_label:   false
    # use_as_channel: false
    # cache:          false
  
  # Data transforms
  Resize:
    active:         false
    size:           64
    interpolation:  bilinear 
  RandomRotation:
    active:         true 
  RandomCrop:
    active:         true
    size:           32 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5

Debug:
  train:
    value: false

