Main:
  train:
    value: true
  validate:
    value: false
  test:
    value: false
  generate:
    value: false

Debug:
  train:
    value: true

Data:
  Data_Split: 1.0

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  climate: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  
  # Data transforms
  Resize:
    active:         true
    size:           64
    interpolation:  bilinear 
  RandomRotation:
    active:         false 
  RandomCrop:
    active:         true
    size:           16 
  FiveCrop:
    active:         false 
  TenCrop:
    active:         false 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5


PTG_Model: 
  train:
    value: true

Hyperparameters:
  train:
    value: true

Training:
  train:
    value: true

Variational_Auto_Encoder:
  external: cfg/vae/vae.yaml
  selection: VAE_1x16x16_4x8x8
  only_load_selection: true
  read_only: true



