# =============================================================================
# MAIN
# =============================================================================
Main:
  train:      true
  validate:   false
  test:       false
  generate:   true

  load_model: true

  img2img: true
  test_image: test_image.png


# =============================================================================
# TRAINING
# =============================================================================
Training:  
  epochs:           3000
  batch_size:       64
  learning_rate:    4.5e-6
  logging_steps:    10
  num_workers:      2
  Save_after_epoch: true
  Data_Split:       1.0

  Validation:
    z_score: 3

# =============================================================================
# MODEL
# =============================================================================
Model:
  # external: cfg/vae/vae.yaml
  # selection: VAE_1x256x256_4x32x32_167k
  external: cfg/diffusion/ddpm.yaml
  selection: latent_terrain_diffusion_max
  only_load_selection: true
  read_only: true

# =============================================================================
# DATA
# =============================================================================
Data:
  use_MNIST:      false

  DEM_List:       SRTM_GL1_50_over_list.txt
  DEM_Dataset:    SRTM_GL1_512x512
  Cache_DEMs:     true
  loader_workers: 8
  # < 1 -> We take all in the specified list
  amount_dems:    0

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   true
    use_as_channel: false
    cache:          true
  Climate: 
    use_as_label:   true
    use_as_channel: false
    cache:          true
  
  # Data transforms
  RandomCrop:
    active:         true
    size:           256 
  RandomRotation:
    active:         true 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5

Debug:
  print_only_rank_zero: false
