# =============================================================================
# MAIN
# =============================================================================
Main:
  train:      true
  validate:   false
  test:       false
  generate:   false

  load_model: false

  use_MNIST:  false

# =============================================================================
# TRAINING
# =============================================================================
Training:  
  epochs:           400
  batch_size:       64
  learning_rate:    4.5e-6
  logging_steps:    10
  num_workers:      2
  Save_after_epoch: true

  Validation:
    z_score: 3

# =============================================================================
# MODEL
# =============================================================================
Model:
  # external: cfg/vae/vae.yaml
  # selection: VAE_full_test
  external: cfg/diffusion/ddpm.yaml
  selection: latent_diffusion_test
  only_load_selection: true
  read_only: true

# =============================================================================
# DATA
# =============================================================================
Data:
  Data_Split: 1.0
  DEM_List: SRTM_GL1_10_list.txt
  DEM_Dataset: SRTM_GL1_64x64
  Cache_DEMs: true

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  Climate: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   true
    use_as_channel: false
    cache:          true
    # use_as_label:   false
    # use_as_channel: false
    # cache:          false
  
  # Data transforms
  Resize:
    active:         false
    size:           64
    interpolation:  bilinear 
  RandomRotation:
    active:         false 
  RandomCrop:
    active:         false # true
    size:           32 
  FiveCrop:
    active:         false 
  TenCrop:
    active:         false 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5


PTG_Model: 
  train:
    value: true

Hyperparameters:
  train:
    value: true

Debug:
  train:
    value: false

