# =============================================================================
# MAIN
# =============================================================================
Main:
  train:      true
  validate:   false
  test:       false
  generate:   0 #true

  load_model: 0 # true


# =============================================================================
# TRAINING
# =============================================================================
Training:  
  epochs:           3000
  batch_size:       128
  learning_rate:    4.5e-6
  logging_steps:    10
  num_workers:      2
  Save_after_epoch: true
  Data_Split:       1.0

  Validation:
    z_score: 3

# =============================================================================
# MODEL
# =============================================================================
Model:
  external: cfg/vae/vae.yaml
  selection: VAE_test_just_like_sd
  # external: cfg/diffusion/ddpm.yaml
  # selection: latent_diffusion_test_new_scale
  only_load_selection: true
  read_only: true

# =============================================================================
# DATA
# =============================================================================
Data:
  use_MNIST:      false

  DEM_List:       SRTM_GL1_50_over_list.txt
  DEM_Dataset:    SRTM_GL1_64x64
  Cache_DEMs:     true
  loader_workers: 2
  # < 1 -> We take all in the specified list
  amount_dems:    0

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  Climate: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   false
    use_as_channel: false
    cache:          false
    # use_as_label:   false
    # use_as_channel: false
    # cache:          false
  
  # Data transforms
  RandomCrop:
    active:         true
    size:           32 
  RandomRotation:
    active:         true 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5

Debug:
  print_only_rank_zero: false
