Main:
  train:    true
  validate: false
  test:     false
  generate: false

  use_MNIST: true
  load_model: false


Debug:
  train:
    value: false

Training:  
  epochs:           200
  batch_size:       128
  learning_rate:    4.5e-6
  logging_steps:    10
  cpu_count:        2
  Save_after_epoch: true

  Validation:
    z_score: 3


Data:
  Data_Split: 1.0
  DEM_List: SRTM_GL1_0-3213_list.txt
  DEM_Dataset: SRTM_GL1_64x64

  # Datasets
  GLiM:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  climate: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  DSMW: 
    use_as_label:   false
    use_as_channel: false
    cache:          false
  GTC:
    use_as_label:   false
    use_as_channel: false
    cache:          false
  
  # Data transforms
  Resize:
    active:         false
    size:           64
    interpolation:  bilinear 
  RandomRotation:
    active:         false 
  RandomCrop:
    active:         true
    size:           32 
  FiveCrop:
    active:         false 
  TenCrop:
    active:         false 
  RandomHorizontalFlip:
    active:         true 
    probability:    0.5
  RandomVerticalFlip:
    active:         true 
    probability:    0.5


PTG_Model: 
  train:
    value: true

Hyperparameters:
  train:
    value: true

Model:
  external: cfg/vae/vae.yaml
  selection: VAE_1x16x16_4x4x4_biggerbeta
  only_load_selection: true
  read_only: true



