VAE_1x32x32_4x8x8:
  name: VAE_1x32x32_4x8x8
  description: "Test VAE for sanity checks"
  
  data_num_channels: 1
  data_resolution_x: 32
  data_resolution_y: 32

  latent_num_channels: 4
  latent_resolution_x: 8
  latent_resolution_y: 8
  
  # Defines the structure of the vae
  architecture:
    ResNet_blocks_per_layer: 2
    starting_channels: 128
    dropout: 0.0
    non_linearity: SiLU
    # Each channel multiplier denotes a resolution block
    # One block will be added with the last channel multiplier for the 
    # bottle neck
    channel_multipliers:
    - 1
    - 2
    - 4

    # resolution blocks at which we should use attention
    attention_resolutions:
    - 4

  # Training parameters
  training:
    learning_rate: 0.0001


